name: CI/CD Pipeline

on:
  push:
    branches: [ main, staging, develop ]
  pull_request:
    branches: [ main, staging, develop ]

jobs:
  Full-CI-Pipeline:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Scan code quality
      uses: rcowsill/workflow-scan-action@v3.0.0

    - name: Notify Discord through Webhook
      run: |
        curl -v \
        -H "Content-Type: application/json" \
        -X POST \
        -d '{"content":"Deployment to '${{ github.ref }}' was successful. Image: my-app:'${{ github.sha }}'"}' \
        ${{ secrets.DISCORD_WEBHOOK_URL }}
